feat: always use native wt fonts for yeartext
sircharlo/meeting-media-manager pull request #814
Opened 2022-12-04 13:46 UTC by mtdvlpr

I found the Wt-ClearText-Bold font and the JW-Icons font which are used for the yeartext. This means that we can now always show the yeartext in the native font and we can show the JW logo for any platform.

2022-12-04 13:50 UTC, sircharlo requested changes
Could we fetch the font files on runtime instead of including them in the app's files? 

It's one thing to fetch a file and use it, it's another completely to bundle a file and redistribute it. I'm not sure the license agreement would allow for that. 

I've been very careful to never bundle anything that isn't "mine" with the app, and to fetch what is needed at runtime from the APIs directly. What do you think?

2022-12-04 13:52 UTC, mtdvlpr commented
Agreed!

2022-12-04 14:45 UTC, mtdvlpr commented
@sircharlo, done :)

2022-12-07 10:08 UTC, mtdvlpr commented
@sircharlo, do you think we should keep the search for local Watchtower Library files and prefer that over these runtime fetched files? I think the logic itself should stay, since the discovered endpoints could be changed in the future, but we might set the runtime fetched files as the default and the WT Library as a fallback. What do you think?

2022-12-07 14:59 UTC, mtdvlpr commented
@sircharlo, done! Guess we can merge this now?

2022-12-07 15:13 UTC, sircharlo commented
Absolutely!

2022-12-07 15:13 UTC, sircharlo approved these changes

2022-12-07 15:13 UTC, sircharlo commented on src/renderer/plugins/jw.ts
> +    if (!existsSync(fontPath) || statSync(fontPath).size === 0) {
Would it be better to send a HEAD request to get the filesize of the remote file, and then to compare the local filesize with the remote filesize and download if the filesize is different (ie, the remote file was updated)?
Or are you more comfortable with "download it once, forget about it after"?
I don't see a problem with either method, honestly.

2022-12-07 15:42 UTC, mtdvlpr commented on src/renderer/plugins/jw.ts
> +    if (!existsSync(fontPath) || statSync(fontPath).size === 0) {
Done. I also moved the fetching to inside the yeartext fetch if. So it will only fetch the fonts if the yeartext is (forcefully) fetched.

2022-12-07 15:43 UTC, sircharlo commented on src/renderer/plugins/jw.ts
> +    if (!existsSync(fontPath) || statSync(fontPath).size === 0) {
Smart! That way, the fonts will update once a year, correct?

2022-12-07 15:57 UTC, sircharlo approved these changes
👍 👍 👍

2022-12-07 15:59 UTC, mtdvlpr commented on src/renderer/plugins/jw.ts
> +    if (!existsSync(fontPath) || statSync(fontPath).size === 0) {
Now this will :)

2022-12-07 16:20 UTC, merged